version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      nextjs:
        patterns:
          - 'next'
          - '@next/*'
          - 'eslint-config-next'
          - 'web-vitals'
      eslint-prettier:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
        exclude-patterns:
          - 'eslint-config-next'
          - 'prettier-plugin-tailwindcss'
      mui-emotion:
        patterns:
          - '@emotion/*'
          - '@mui/*'
      react:
        patterns:
          - '@types/react*'
          - 'react'
          - 'react-dom'
      tailwindcss:
        patterns:
          - 'autoprefixer'
          - 'postcss'
          - 'tailwindcss'
          - 'typewind'
          - 'prettier-plugin-tailwindcss'
      redux:
        patterns:
          - 'react-redux'
          - '@reduxjs/toolkit'
      misc:
        patterns:
          - '*'
        exclude-patterns:
          - 'next'
          - '@next/*'
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
          - '@supabase/*'
          - '@types/react*'
          - 'react*'
          - 'autoprefixer'
          - 'postcss'
          - 'tailwindcss'
